# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=1000000, null=True)),
                ('description', models.TextField(blank=True, max_length=1000000, null=True)),
                ('link', models.URLField(default='https://sadieparker.net', max_length=1000000)),
                ('image_name', models.TextField(default='default', max_length=2000)),
            ],
        ),
    ]
