# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_name',
            field=models.CharField(default='default', max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
