# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170714_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
