# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_project_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='time',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='project',
            name='tools_used',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
