# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170717_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_name',
        ),
        migrations.AddField(
            model_name='project',
            name='proj_image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
