# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170902_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.URLField(blank=True, max_length=100000, null=True),
        ),
    ]
