# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_project_source_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, max_length=1000000, null=True),
        ),
    ]
