# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170902_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
