# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20180713_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='link',
            field=models.URLField(blank=True, max_length=1000000, null=True),
        ),
    ]
