# Generated by Django 3.0.5 on 2020-04-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_review_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_data_uri',
            field=models.CharField(blank=True, default='', max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='album_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
